name: "USBRelay MQTT Bridge"
version: "0.1.0"
slug: "usbrelay_mqtt"
description: "Bridges USB HID relay boards to MQTT for Home Assistant."
arch:
  - aarch64
  - amd64
  - armv7
init: false
startup: application
boot: auto
ingress: false
usb: true
udev: true
icon: "icon.png"
logo: "logo.png"
options:
  mqtt_host: 172.30.32.1
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  base_topic: "usbrelay"
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: str
  base_topic: str
